/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AupRouteImport } from './routes/aup'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as HomeownerRouteImport } from './routes/homeowner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManageRouteRouteImport } from './routes/manage/route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SaasRouteImport } from './routes/saas'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SlaRouteImport } from './routes/sla'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppBookRouteImport } from './routes/app/book'
import { Route as AppLeadsRouteImport } from './routes/app/leads'
import { Route as AppMarketRouteImport } from './routes/app/market'
import { Route as AppNewRouteImport } from './routes/app/new'
import { Route as AppOnboardRouteImport } from './routes/app/onboard'
import { Route as AppPropertiesRouteImport } from './routes/app/properties'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppTemplatesRouteImport } from './routes/app/templates'
import { Route as ClaimTokenRouteImport } from './routes/claim.$token'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeIdRouteImport } from './routes/home/$id'
import { Route as HomeAddRouteImport } from './routes/home/add'
import { Route as HomeSettingsRouteImport } from './routes/home/settings'
import { Route as HouseTokenRouteImport } from './routes/house.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ManageIndexRouteImport } from './routes/manage/index'
import { Route as ManageIdRouteImport } from './routes/manage/$id'
import { Route as ManageAddRouteImport } from './routes/manage/add'
import { Route as ManageOpenRouteImport } from './routes/manage/open'
import { Route as ManageSettingsRouteImport } from './routes/manage/settings'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as RfpTokenRouteImport } from './routes/rfp.$token'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as ShopOpenRouteImport } from './routes/shop.open'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as AppPropertiesIdRouteImport } from './routes/app/properties.$id'
import { Route as AppProposalsIdRouteImport } from './routes/app/proposals.$id'
import { Route as PTokenAcceptedRouteImport } from './routes/p.$token.accepted'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AupRoute = AupRouteImport.update({
  id: '/aup',
  path: '/aup',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeownerRoute = HomeownerRouteImport.update({
  id: '/homeowner',
  path: '/homeowner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRouteRoute = ManageRouteRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SaasRoute = SaasRouteImport.update({
  id: '/saas',
  path: '/saas',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SlaRoute = SlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBookRoute = AppBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardRoute = AppOnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPropertiesRoute = AppPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRouteRoute,
} as any)
const ClaimTokenRoute = ClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeIdRoute = HomeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeAddRoute = HomeAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeSettingsRoute = HomeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HouseTokenRoute = HouseTokenRouteImport.update({
  id: '/house/$token',
  path: '/house/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageRouteRoute,
} as any)
const ManageIdRoute = ManageIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ManageRouteRoute,
} as any)
const ManageAddRoute = ManageAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => ManageRouteRoute,
} as any)
const ManageOpenRoute = ManageOpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => ManageRouteRoute,
} as any)
const ManageSettingsRoute = ManageSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ManageRouteRoute,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RfpTokenRoute = RfpTokenRouteImport.update({
  id: '/rfp/$token',
  path: '/rfp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopOpenRoute = ShopOpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => ShopRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPropertiesIdRoute = AppPropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPropertiesRoute,
} as any)
const AppProposalsIdRoute = AppProposalsIdRouteImport.update({
  id: '/proposals/$id',
  path: '/proposals/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const PTokenAcceptedRoute = PTokenAcceptedRouteImport.update({
  id: '/accepted',
  path: '/accepted',
  getParentRoute: () => PTokenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/manage': typeof ManageRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/aup': typeof AupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/homeowner': typeof HomeownerRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saas': typeof SaasRoute
  '/shop': typeof ShopRouteWithChildren
  '/sla': typeof SlaRoute
  '/terms': typeof TermsRoute
  '/app/book': typeof AppBookRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/market': typeof AppMarketRoute
  '/app/new': typeof AppNewRoute
  '/app/onboard': typeof AppOnboardRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/home/$id': typeof HomeIdRoute
  '/home/add': typeof HomeAddRoute
  '/home/settings': typeof HomeSettingsRoute
  '/house/$token': typeof HouseTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/manage/$id': typeof ManageIdRoute
  '/manage/add': typeof ManageAddRoute
  '/manage/open': typeof ManageOpenRoute
  '/manage/settings': typeof ManageSettingsRoute
  '/p/$token': typeof PTokenRouteWithChildren
  '/rfp/$token': typeof RfpTokenRoute
  '/s/$slug': typeof SSlugRoute
  '/shop/open': typeof ShopOpenRoute
  '/app/': typeof AppIndexRoute
  '/home/': typeof HomeIndexRoute
  '/manage/': typeof ManageIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/app/properties/$id': typeof AppPropertiesIdRoute
  '/app/proposals/$id': typeof AppProposalsIdRoute
  '/p/$token/accepted': typeof PTokenAcceptedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/aup': typeof AupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/homeowner': typeof HomeownerRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saas': typeof SaasRoute
  '/shop': typeof ShopRouteWithChildren
  '/sla': typeof SlaRoute
  '/terms': typeof TermsRoute
  '/app/book': typeof AppBookRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/market': typeof AppMarketRoute
  '/app/new': typeof AppNewRoute
  '/app/onboard': typeof AppOnboardRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/home/$id': typeof HomeIdRoute
  '/home/add': typeof HomeAddRoute
  '/home/settings': typeof HomeSettingsRoute
  '/house/$token': typeof HouseTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/manage/$id': typeof ManageIdRoute
  '/manage/add': typeof ManageAddRoute
  '/manage/open': typeof ManageOpenRoute
  '/manage/settings': typeof ManageSettingsRoute
  '/p/$token': typeof PTokenRouteWithChildren
  '/rfp/$token': typeof RfpTokenRoute
  '/s/$slug': typeof SSlugRoute
  '/shop/open': typeof ShopOpenRoute
  '/app': typeof AppIndexRoute
  '/home': typeof HomeIndexRoute
  '/manage': typeof ManageIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/app/properties/$id': typeof AppPropertiesIdRoute
  '/app/proposals/$id': typeof AppProposalsIdRoute
  '/p/$token/accepted': typeof PTokenAcceptedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/manage': typeof ManageRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/aup': typeof AupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/homeowner': typeof HomeownerRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saas': typeof SaasRoute
  '/shop': typeof ShopRouteWithChildren
  '/sla': typeof SlaRoute
  '/terms': typeof TermsRoute
  '/app/book': typeof AppBookRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/market': typeof AppMarketRoute
  '/app/new': typeof AppNewRoute
  '/app/onboard': typeof AppOnboardRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/home/$id': typeof HomeIdRoute
  '/home/add': typeof HomeAddRoute
  '/home/settings': typeof HomeSettingsRoute
  '/house/$token': typeof HouseTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/manage/$id': typeof ManageIdRoute
  '/manage/add': typeof ManageAddRoute
  '/manage/open': typeof ManageOpenRoute
  '/manage/settings': typeof ManageSettingsRoute
  '/p/$token': typeof PTokenRouteWithChildren
  '/rfp/$token': typeof RfpTokenRoute
  '/s/$slug': typeof SSlugRoute
  '/shop/open': typeof ShopOpenRoute
  '/app/': typeof AppIndexRoute
  '/home/': typeof HomeIndexRoute
  '/manage/': typeof ManageIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/app/properties/$id': typeof AppPropertiesIdRoute
  '/app/proposals/$id': typeof AppProposalsIdRoute
  '/p/$token/accepted': typeof PTokenAcceptedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/home'
    | '/manage'
    | '/account'
    | '/aup'
    | '/forgot-password'
    | '/homeowner'
    | '/login'
    | '/reset-password'
    | '/saas'
    | '/shop'
    | '/sla'
    | '/terms'
    | '/app/book'
    | '/app/leads'
    | '/app/market'
    | '/app/new'
    | '/app/onboard'
    | '/app/properties'
    | '/app/settings'
    | '/app/templates'
    | '/claim/$token'
    | '/home/$id'
    | '/home/add'
    | '/home/settings'
    | '/house/$token'
    | '/invite/$token'
    | '/manage/$id'
    | '/manage/add'
    | '/manage/open'
    | '/manage/settings'
    | '/p/$token'
    | '/rfp/$token'
    | '/s/$slug'
    | '/shop/open'
    | '/app/'
    | '/home/'
    | '/manage/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/app/properties/$id'
    | '/app/proposals/$id'
    | '/p/$token/accepted'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/aup'
    | '/forgot-password'
    | '/homeowner'
    | '/login'
    | '/reset-password'
    | '/saas'
    | '/shop'
    | '/sla'
    | '/terms'
    | '/app/book'
    | '/app/leads'
    | '/app/market'
    | '/app/new'
    | '/app/onboard'
    | '/app/properties'
    | '/app/settings'
    | '/app/templates'
    | '/claim/$token'
    | '/home/$id'
    | '/home/add'
    | '/home/settings'
    | '/house/$token'
    | '/invite/$token'
    | '/manage/$id'
    | '/manage/add'
    | '/manage/open'
    | '/manage/settings'
    | '/p/$token'
    | '/rfp/$token'
    | '/s/$slug'
    | '/shop/open'
    | '/app'
    | '/home'
    | '/manage'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/app/properties/$id'
    | '/app/proposals/$id'
    | '/p/$token/accepted'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/home'
    | '/manage'
    | '/account'
    | '/aup'
    | '/forgot-password'
    | '/homeowner'
    | '/login'
    | '/reset-password'
    | '/saas'
    | '/shop'
    | '/sla'
    | '/terms'
    | '/app/book'
    | '/app/leads'
    | '/app/market'
    | '/app/new'
    | '/app/onboard'
    | '/app/properties'
    | '/app/settings'
    | '/app/templates'
    | '/claim/$token'
    | '/home/$id'
    | '/home/add'
    | '/home/settings'
    | '/house/$token'
    | '/invite/$token'
    | '/manage/$id'
    | '/manage/add'
    | '/manage/open'
    | '/manage/settings'
    | '/p/$token'
    | '/rfp/$token'
    | '/s/$slug'
    | '/shop/open'
    | '/app/'
    | '/home/'
    | '/manage/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/app/properties/$id'
    | '/app/proposals/$id'
    | '/p/$token/accepted'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  ManageRouteRoute: typeof ManageRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  AupRoute: typeof AupRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeownerRoute: typeof HomeownerRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SaasRoute: typeof SaasRoute
  ShopRoute: typeof ShopRouteWithChildren
  SlaRoute: typeof SlaRoute
  TermsRoute: typeof TermsRoute
  ClaimTokenRoute: typeof ClaimTokenRoute
  HouseTokenRoute: typeof HouseTokenRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PTokenRoute: typeof PTokenRouteWithChildren
  RfpTokenRoute: typeof RfpTokenRoute
  SSlugRoute: typeof SSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aup': {
      id: '/aup'
      path: '/aup'
      fullPath: '/aup'
      preLoaderRoute: typeof AupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homeowner': {
      id: '/homeowner'
      path: '/homeowner'
      fullPath: '/homeowner'
      preLoaderRoute: typeof HomeownerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saas': {
      id: '/saas'
      path: '/saas'
      fullPath: '/saas'
      preLoaderRoute: typeof SaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sla': {
      id: '/sla'
      path: '/sla'
      fullPath: '/sla'
      preLoaderRoute: typeof SlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/book': {
      id: '/app/book'
      path: '/book'
      fullPath: '/app/book'
      preLoaderRoute: typeof AppBookRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/market': {
      id: '/app/market'
      path: '/market'
      fullPath: '/app/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/new': {
      id: '/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/onboard': {
      id: '/app/onboard'
      path: '/onboard'
      fullPath: '/app/onboard'
      preLoaderRoute: typeof AppOnboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/properties': {
      id: '/app/properties'
      path: '/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AppPropertiesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/claim/$token': {
      id: '/claim/$token'
      path: '/claim/$token'
      fullPath: '/claim/$token'
      preLoaderRoute: typeof ClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/$id': {
      id: '/home/$id'
      path: '/$id'
      fullPath: '/home/$id'
      preLoaderRoute: typeof HomeIdRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/add': {
      id: '/home/add'
      path: '/add'
      fullPath: '/home/add'
      preLoaderRoute: typeof HomeAddRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/settings': {
      id: '/home/settings'
      path: '/settings'
      fullPath: '/home/settings'
      preLoaderRoute: typeof HomeSettingsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/house/$token': {
      id: '/house/$token'
      path: '/house/$token'
      fullPath: '/house/$token'
      preLoaderRoute: typeof HouseTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof ManageRouteRoute
    }
    '/manage/$id': {
      id: '/manage/$id'
      path: '/$id'
      fullPath: '/manage/$id'
      preLoaderRoute: typeof ManageIdRouteImport
      parentRoute: typeof ManageRouteRoute
    }
    '/manage/add': {
      id: '/manage/add'
      path: '/add'
      fullPath: '/manage/add'
      preLoaderRoute: typeof ManageAddRouteImport
      parentRoute: typeof ManageRouteRoute
    }
    '/manage/open': {
      id: '/manage/open'
      path: '/open'
      fullPath: '/manage/open'
      preLoaderRoute: typeof ManageOpenRouteImport
      parentRoute: typeof ManageRouteRoute
    }
    '/manage/settings': {
      id: '/manage/settings'
      path: '/settings'
      fullPath: '/manage/settings'
      preLoaderRoute: typeof ManageSettingsRouteImport
      parentRoute: typeof ManageRouteRoute
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfp/$token': {
      id: '/rfp/$token'
      path: '/rfp/$token'
      fullPath: '/rfp/$token'
      preLoaderRoute: typeof RfpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/open': {
      id: '/shop/open'
      path: '/open'
      fullPath: '/shop/open'
      preLoaderRoute: typeof ShopOpenRouteImport
      parentRoute: typeof ShopRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/properties/$id': {
      id: '/app/properties/$id'
      path: '/$id'
      fullPath: '/app/properties/$id'
      preLoaderRoute: typeof AppPropertiesIdRouteImport
      parentRoute: typeof AppPropertiesRoute
    }
    '/app/proposals/$id': {
      id: '/app/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/app/proposals/$id'
      preLoaderRoute: typeof AppProposalsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/p/$token/accepted': {
      id: '/p/$token/accepted'
      path: '/accepted'
      fullPath: '/p/$token/accepted'
      preLoaderRoute: typeof PTokenAcceptedRouteImport
      parentRoute: typeof PTokenRoute
    }
  }
}

interface AppPropertiesRouteChildren {
  AppPropertiesIdRoute: typeof AppPropertiesIdRoute
}

const AppPropertiesRouteChildren: AppPropertiesRouteChildren = {
  AppPropertiesIdRoute: AppPropertiesIdRoute,
}

const AppPropertiesRouteWithChildren = AppPropertiesRoute._addFileChildren(
  AppPropertiesRouteChildren,
)

interface AppRouteRouteChildren {
  AppBookRoute: typeof AppBookRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMarketRoute: typeof AppMarketRoute
  AppNewRoute: typeof AppNewRoute
  AppOnboardRoute: typeof AppOnboardRoute
  AppPropertiesRoute: typeof AppPropertiesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProposalsIdRoute: typeof AppProposalsIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBookRoute: AppBookRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMarketRoute: AppMarketRoute,
  AppNewRoute: AppNewRoute,
  AppOnboardRoute: AppOnboardRoute,
  AppPropertiesRoute: AppPropertiesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppIndexRoute: AppIndexRoute,
  AppProposalsIdRoute: AppProposalsIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeIdRoute: typeof HomeIdRoute
  HomeAddRoute: typeof HomeAddRoute
  HomeSettingsRoute: typeof HomeSettingsRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeIdRoute: HomeIdRoute,
  HomeAddRoute: HomeAddRoute,
  HomeSettingsRoute: HomeSettingsRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

interface ManageRouteRouteChildren {
  ManageIdRoute: typeof ManageIdRoute
  ManageAddRoute: typeof ManageAddRoute
  ManageOpenRoute: typeof ManageOpenRoute
  ManageSettingsRoute: typeof ManageSettingsRoute
  ManageIndexRoute: typeof ManageIndexRoute
}

const ManageRouteRouteChildren: ManageRouteRouteChildren = {
  ManageIdRoute: ManageIdRoute,
  ManageAddRoute: ManageAddRoute,
  ManageOpenRoute: ManageOpenRoute,
  ManageSettingsRoute: ManageSettingsRoute,
  ManageIndexRoute: ManageIndexRoute,
}

const ManageRouteRouteWithChildren = ManageRouteRoute._addFileChildren(
  ManageRouteRouteChildren,
)

interface ShopRouteChildren {
  ShopOpenRoute: typeof ShopOpenRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopOpenRoute: ShopOpenRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface PTokenRouteChildren {
  PTokenAcceptedRoute: typeof PTokenAcceptedRoute
}

const PTokenRouteChildren: PTokenRouteChildren = {
  PTokenAcceptedRoute: PTokenAcceptedRoute,
}

const PTokenRouteWithChildren =
  PTokenRoute._addFileChildren(PTokenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  ManageRouteRoute: ManageRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  AupRoute: AupRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeownerRoute: HomeownerRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SaasRoute: SaasRoute,
  ShopRoute: ShopRouteWithChildren,
  SlaRoute: SlaRoute,
  TermsRoute: TermsRoute,
  ClaimTokenRoute: ClaimTokenRoute,
  HouseTokenRoute: HouseTokenRoute,
  InviteTokenRoute: InviteTokenRoute,
  PTokenRoute: PTokenRouteWithChildren,
  RfpTokenRoute: RfpTokenRoute,
  SSlugRoute: SSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
