/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as HomeownersRouteImport } from './routes/homeowners'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyRouteImport } from './routes/my'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppBookRouteImport } from './routes/app/book'
import { Route as AppLeadsRouteImport } from './routes/app/leads'
import { Route as AppMarketRouteImport } from './routes/app/market'
import { Route as AppNewRouteImport } from './routes/app/new'
import { Route as AppOnboardRouteImport } from './routes/app/onboard'
import { Route as AppPropertiesRouteImport } from './routes/app/properties'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppTemplatesRouteImport } from './routes/app/templates'
import { Route as ClaimTokenRouteImport } from './routes/claim.$token'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeIdRouteImport } from './routes/home/$id'
import { Route as HomeAddRouteImport } from './routes/home/add'
import { Route as HouseTokenRouteImport } from './routes/house.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as RfpTokenRouteImport } from './routes/rfp.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppPropertiesIdRouteImport } from './routes/app/properties.$id'
import { Route as AppProposalsIdRouteImport } from './routes/app/proposals.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeownersRoute = HomeownersRouteImport.update({
  id: '/homeowners',
  path: '/homeowners',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBookRoute = AppBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardRoute = AppOnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPropertiesRoute = AppPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRouteRoute,
} as any)
const ClaimTokenRoute = ClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeIdRoute = HomeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeAddRoute = HomeAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HouseTokenRoute = HouseTokenRouteImport.update({
  id: '/house/$token',
  path: '/house/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RfpTokenRoute = RfpTokenRouteImport.update({
  id: '/rfp/$token',
  path: '/rfp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPropertiesIdRoute = AppPropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPropertiesRoute,
} as any)
const AppProposalsIdRoute = AppProposalsIdRouteImport.update({
  id: '/proposals/$id',
  path: '/proposals/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/homeowners': typeof HomeownersRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRoute
  '/shop': typeof ShopRoute
  '/app/book': typeof AppBookRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/market': typeof AppMarketRoute
  '/app/new': typeof AppNewRoute
  '/app/onboard': typeof AppOnboardRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/home/$id': typeof HomeIdRoute
  '/home/add': typeof HomeAddRoute
  '/house/$token': typeof HouseTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$token': typeof PTokenRoute
  '/rfp/$token': typeof RfpTokenRoute
  '/app/': typeof AppIndexRoute
  '/home/': typeof HomeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/properties/$id': typeof AppPropertiesIdRoute
  '/app/proposals/$id': typeof AppProposalsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/homeowners': typeof HomeownersRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRoute
  '/shop': typeof ShopRoute
  '/app/book': typeof AppBookRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/market': typeof AppMarketRoute
  '/app/new': typeof AppNewRoute
  '/app/onboard': typeof AppOnboardRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/home/$id': typeof HomeIdRoute
  '/home/add': typeof HomeAddRoute
  '/house/$token': typeof HouseTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$token': typeof PTokenRoute
  '/rfp/$token': typeof RfpTokenRoute
  '/app': typeof AppIndexRoute
  '/home': typeof HomeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/properties/$id': typeof AppPropertiesIdRoute
  '/app/proposals/$id': typeof AppProposalsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/homeowners': typeof HomeownersRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRoute
  '/shop': typeof ShopRoute
  '/app/book': typeof AppBookRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/market': typeof AppMarketRoute
  '/app/new': typeof AppNewRoute
  '/app/onboard': typeof AppOnboardRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/home/$id': typeof HomeIdRoute
  '/home/add': typeof HomeAddRoute
  '/house/$token': typeof HouseTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$token': typeof PTokenRoute
  '/rfp/$token': typeof RfpTokenRoute
  '/app/': typeof AppIndexRoute
  '/home/': typeof HomeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/properties/$id': typeof AppPropertiesIdRoute
  '/app/proposals/$id': typeof AppProposalsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/home'
    | '/homeowners'
    | '/login'
    | '/my'
    | '/shop'
    | '/app/book'
    | '/app/leads'
    | '/app/market'
    | '/app/new'
    | '/app/onboard'
    | '/app/properties'
    | '/app/settings'
    | '/app/templates'
    | '/claim/$token'
    | '/home/$id'
    | '/home/add'
    | '/house/$token'
    | '/invite/$token'
    | '/p/$token'
    | '/rfp/$token'
    | '/app/'
    | '/home/'
    | '/api/auth/$'
    | '/app/properties/$id'
    | '/app/proposals/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/homeowners'
    | '/login'
    | '/my'
    | '/shop'
    | '/app/book'
    | '/app/leads'
    | '/app/market'
    | '/app/new'
    | '/app/onboard'
    | '/app/properties'
    | '/app/settings'
    | '/app/templates'
    | '/claim/$token'
    | '/home/$id'
    | '/home/add'
    | '/house/$token'
    | '/invite/$token'
    | '/p/$token'
    | '/rfp/$token'
    | '/app'
    | '/home'
    | '/api/auth/$'
    | '/app/properties/$id'
    | '/app/proposals/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/home'
    | '/homeowners'
    | '/login'
    | '/my'
    | '/shop'
    | '/app/book'
    | '/app/leads'
    | '/app/market'
    | '/app/new'
    | '/app/onboard'
    | '/app/properties'
    | '/app/settings'
    | '/app/templates'
    | '/claim/$token'
    | '/home/$id'
    | '/home/add'
    | '/house/$token'
    | '/invite/$token'
    | '/p/$token'
    | '/rfp/$token'
    | '/app/'
    | '/home/'
    | '/api/auth/$'
    | '/app/properties/$id'
    | '/app/proposals/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  HomeownersRoute: typeof HomeownersRoute
  LoginRoute: typeof LoginRoute
  MyRoute: typeof MyRoute
  ShopRoute: typeof ShopRoute
  ClaimTokenRoute: typeof ClaimTokenRoute
  HouseTokenRoute: typeof HouseTokenRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PTokenRoute: typeof PTokenRoute
  RfpTokenRoute: typeof RfpTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homeowners': {
      id: '/homeowners'
      path: '/homeowners'
      fullPath: '/homeowners'
      preLoaderRoute: typeof HomeownersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/book': {
      id: '/app/book'
      path: '/book'
      fullPath: '/app/book'
      preLoaderRoute: typeof AppBookRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/market': {
      id: '/app/market'
      path: '/market'
      fullPath: '/app/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/new': {
      id: '/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/onboard': {
      id: '/app/onboard'
      path: '/onboard'
      fullPath: '/app/onboard'
      preLoaderRoute: typeof AppOnboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/properties': {
      id: '/app/properties'
      path: '/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AppPropertiesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/claim/$token': {
      id: '/claim/$token'
      path: '/claim/$token'
      fullPath: '/claim/$token'
      preLoaderRoute: typeof ClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/$id': {
      id: '/home/$id'
      path: '/$id'
      fullPath: '/home/$id'
      preLoaderRoute: typeof HomeIdRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/add': {
      id: '/home/add'
      path: '/add'
      fullPath: '/home/add'
      preLoaderRoute: typeof HomeAddRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/house/$token': {
      id: '/house/$token'
      path: '/house/$token'
      fullPath: '/house/$token'
      preLoaderRoute: typeof HouseTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfp/$token': {
      id: '/rfp/$token'
      path: '/rfp/$token'
      fullPath: '/rfp/$token'
      preLoaderRoute: typeof RfpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/properties/$id': {
      id: '/app/properties/$id'
      path: '/$id'
      fullPath: '/app/properties/$id'
      preLoaderRoute: typeof AppPropertiesIdRouteImport
      parentRoute: typeof AppPropertiesRoute
    }
    '/app/proposals/$id': {
      id: '/app/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/app/proposals/$id'
      preLoaderRoute: typeof AppProposalsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppPropertiesRouteChildren {
  AppPropertiesIdRoute: typeof AppPropertiesIdRoute
}

const AppPropertiesRouteChildren: AppPropertiesRouteChildren = {
  AppPropertiesIdRoute: AppPropertiesIdRoute,
}

const AppPropertiesRouteWithChildren = AppPropertiesRoute._addFileChildren(
  AppPropertiesRouteChildren,
)

interface AppRouteRouteChildren {
  AppBookRoute: typeof AppBookRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMarketRoute: typeof AppMarketRoute
  AppNewRoute: typeof AppNewRoute
  AppOnboardRoute: typeof AppOnboardRoute
  AppPropertiesRoute: typeof AppPropertiesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProposalsIdRoute: typeof AppProposalsIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBookRoute: AppBookRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMarketRoute: AppMarketRoute,
  AppNewRoute: AppNewRoute,
  AppOnboardRoute: AppOnboardRoute,
  AppPropertiesRoute: AppPropertiesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppIndexRoute: AppIndexRoute,
  AppProposalsIdRoute: AppProposalsIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeIdRoute: typeof HomeIdRoute
  HomeAddRoute: typeof HomeAddRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeIdRoute: HomeIdRoute,
  HomeAddRoute: HomeAddRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  HomeownersRoute: HomeownersRoute,
  LoginRoute: LoginRoute,
  MyRoute: MyRoute,
  ShopRoute: ShopRoute,
  ClaimTokenRoute: ClaimTokenRoute,
  HouseTokenRoute: HouseTokenRoute,
  InviteTokenRoute: InviteTokenRoute,
  PTokenRoute: PTokenRoute,
  RfpTokenRoute: RfpTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
